INSERT INTO pessoa(nome, cidade, cep) VALUES('Manuela Câmara', 'Rios de Minas', '78170-215');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Clara Moreira', 'Camargo de da Mota', '25820189');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Daniela Porto', 'Teixeira', '65720451');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Alice Costa', 'da Paz do Sul', '49065-298');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maya Costela', 'Borges da Mata', '06571564');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Vitor Hugo Camargo', 'Aragão', '33286-040');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Eduarda Brito', 'Fonseca de da Cruz', '53213-009');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Rebeca Araújo', 'Oliveira do Oeste', '73921824');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Gael Henrique Novaes', 'Cavalcante do Amparo', '25735-524');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Arthur Gabriel Cavalcante', 'Abreu da Prata', '18464329');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Cauê Silva', 'Duarte', '87106947');
INSERT INTO pessoa(nome, cidade, cep) VALUES('João Gabriel da Paz', 'Carvalho', '16469-254');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Melissa Guerra', 'da Cruz', '98307-449');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Anthony Gabriel Câmara', 'Aragão Alegre', '26126695');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Mateus da Mota', 'Porto Alegre', '58537215');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Alice Siqueira', 'Peixoto de Casa Grande', '50144-874');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Sophia Peixoto', 'Siqueira', '85972552');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Henry Gabriel Peixoto', 'Duarte', '20102-027');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Josué Rodrigues', 'Siqueira Verde', '18637-176');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dra. Caroline Monteiro', 'Casa Grande de Minas', '60509-502');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Heloísa Leão', 'Jesus das Flores', '95375252');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Antonella Freitas', 'Sá da Prata', '10309-293');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Julia Costa', 'Araújo', '16995-515');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dr. Levi Pinto', 'Pereira da Mata', '12418052');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Théo Abreu', 'Oliveira', '99786196');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Eloah Martins', 'Andrade de Pereira', '30102768');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Lucas Gabriel Abreu', 'Souza das Pedras', '04237362');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Gael Fernandes', 'da Conceição', '15990562');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Luiza Rocha', 'Câmara', '90886-714');
INSERT INTO pessoa(nome, cidade, cep) VALUES('João Guilherme Farias', 'Costela', '09781-207');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Stephany Ribeiro', 'Barros', '07371-350');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Pietra Pinto', 'Azevedo de Casa Grande', '31961662');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Melissa Abreu', 'Martins da Praia', '66125-185');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Pietro Albuquerque', 'Sá', '68109-873');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Felipe Gonçalves', 'Câmara de da Mota', '29522-693');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Davi Luiz Abreu', 'Cirino', '50283137');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dra. Mariana Viana', 'Sá do Sul', '59976-570');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Oliver das Neves', 'da Mata', '12544-100');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ravi da Costa', 'Brito', '96213-918');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sra. Pietra Martins', 'Carvalho do Sul', '27601008');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Alana Nunes', 'Sales das Flores', '62817-494');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Benicio Caldeira', 'Nunes', '85595369');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Daniel da Costa', 'Nunes de Cirino', '28054-258');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Clara Albuquerque', 'Sales', '06938-447');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Henrique Mendonça', 'Teixeira dos Dourados', '63577-249');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Pietro Rodrigues', 'Almeida de Campos', '27866998');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Fernando Viana', 'Dias', '28549-107');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Diego Pimenta', 'Moreira', '13593-971');
INSERT INTO pessoa(nome, cidade, cep) VALUES('João Pedro Fogaça', 'Fonseca', '31204-216');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Laura Gonçalves', 'Alves Alegre', '90525-623');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dr. Enzo Cirino', 'Silva do Norte', '70164-552');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Josué Teixeira', 'Ribeiro do Campo', '30171686');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Leandro Carvalho', 'Azevedo', '71714-245');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ryan Farias', 'Porto da Serra', '18714928');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Nicolas Mendes', 'Siqueira da Mata', '74090-163');
INSERT INTO pessoa(nome, cidade, cep) VALUES('João Gabriel Pacheco', 'da Cunha', '81128461');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Eduardo Lopes', 'Pastor Verde', '54371063');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Melissa Farias', 'Mendonça', '03138-685');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Vicente Martins', 'Lima', '74989836');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Liz da Cunha', 'Rocha de Goiás', '29552761');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Manuella Sá', 'Araújo', '87114781');
INSERT INTO pessoa(nome, cidade, cep) VALUES('João Lucas Siqueira', 'Albuquerque', '54780162');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Letícia Farias', 'Albuquerque das Pedras', '12082-305');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Guilherme Casa Grande', 'Rios', '07028-682');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Henry Gabriel Garcia', 'Ferreira Alegre', '31067-752');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Isaac Freitas', 'Machado de Goiás', '46778080');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Pietro Sampaio', 'Martins', '48196-490');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Anthony Cunha', 'Pacheco', '37171-294');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dr. Cauã Costela', 'Souza de Rios', '24946-341');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Caroline Lima', 'Marques', '75643-697');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Liz Lima', 'Gonçalves', '68555-574');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Elisa Leão', 'Moreira', '34477476');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Kaique Marques', 'Machado', '51063-189');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Aurora Costela', 'Novais Verde', '56910999');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Heloisa Rios', 'Ferreira da Praia', '16884-352');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Antônio Rezende', 'Almeida do Sul', '23958-794');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Gabrielly da Luz', 'Borges de Caldeira', '49226786');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Benjamin Fogaça', 'Sousa do Sul', '72640795');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Alice Peixoto', 'Guerra', '31669286');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. João Miguel Macedo', 'Pinto', '79732-260');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Antony Costa', 'Nunes', '19464609');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Liz Pimenta', 'Cirino', '79974-235');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Flor Silva', 'Andrade', '21975296');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Júlia Rezende', 'Novaes da Mata', '88589928');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Isabela Gomes', 'Ferreira', '47461251');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Antony Porto', 'Garcia Alegre', '41089-622');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Vinicius Moraes', 'Teixeira do Oeste', '18447-786');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Rafael Moraes', 'da Cunha', '82695-088');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Mirella Lopes', 'Ribeiro', '78204872');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Daniela Castro', 'Pimenta', '85446126');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Caleb Rios', 'Nunes dos Dourados', '76616248');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Asafe Fernandes', 'Melo', '57497655');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Léo Correia', 'Ribeiro do Oeste', '89786944');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Isabel Souza', 'da Rosa', '31935-623');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Camila Cardoso', 'da Costa de Dias', '80265907');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Júlia Albuquerque', 'Jesus', '23535011');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Eduarda da Mata', 'Fonseca do Galho', '92922-875');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Eduarda Borges', 'Casa Grande do Norte', '37497491');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Clarice Duarte', 'da Paz do Galho', '81404-151');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Bruna Ferreira', 'Pereira', '16574374');
INSERT INTO pessoa(nome, cidade, cep) VALUES('João Gabriel Jesus', 'Castro', '05384418');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Melina da Costa', 'da Conceição', '23654965');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Apollo da Paz', 'Ferreira', '55581410');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Pedro Lucas Carvalho', 'Rezende', '63599-763');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dr. Murilo Silva', 'Sales dos Dourados', '94683803');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Flor Cassiano', 'Azevedo de Fernandes', '78421500');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Agatha Jesus', 'Souza de Cassiano', '53414-846');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Theodoro Marques', 'Casa Grande de Goiás', '82711-041');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Luiz Gustavo Cunha', 'Ribeiro do Amparo', '65636-713');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Antony Moura', 'Sá', '41743-442');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Manuela Fonseca', 'Machado do Amparo', '01924-976');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Murilo Sampaio', 'Cardoso das Flores', '30541187');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Sophia Gomes', 'Aparecida', '53495-762');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Raquel da Mota', 'Jesus Paulista', '06087174');
INSERT INTO pessoa(nome, cidade, cep) VALUES('João Vitor Campos', 'Abreu da Serra', '49282-141');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Allana Cavalcanti', 'Lima de Marques', '34938382');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Liam Ribeiro', 'Teixeira', '56300-955');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ester Fonseca', 'Nogueira Alegre', '90382808');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Luiza Brito', 'Nascimento Paulista', '25710-224');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Yuri Gonçalves', 'Freitas', '09209464');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maysa Souza', 'da Cunha', '13135939');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ian Câmara', 'Nunes', '33520-883');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Laura Barros', 'Campos de Camargo', '12254271');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Juan Cunha', 'Ramos', '89596-318');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Clara Campos', 'Albuquerque', '59871-533');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dra. Alana Sá', 'Vargas da Praia', '71336396');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Isaque da Paz', 'Dias', '38601045');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Matheus Rios', 'Silveira Paulista', '83915513');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dr. João Pedro Freitas', 'Souza de Ferreira', '95219-164');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Augusto Freitas', 'Marques de Fernandes', '89554-381');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Gabrielly Machado', 'Borges', '78414772');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Juan Rocha', 'Pinto', '75879-043');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Laís Cavalcanti', 'Araújo das Pedras', '19357-592');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Julia Cardoso', 'da Luz de Rezende', '94056710');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Lorenzo Pires', 'da Rosa', '05573220');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Benício Martins', 'Moura', '79198472');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Rafael Nunes', 'Cunha', '41003503');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Julia Almeida', 'Aragão', '85056-603');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Melina da Rocha', 'Fernandes Paulista', '43137-940');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Mariana Pereira', 'Ferreira do Amparo', '21851927');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Vitória da Rocha', 'Mendonça', '89019473');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Daniela Pinto', 'Gonçalves do Campo', '47761-833');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Isis Cardoso', 'Correia de Machado', '36749-517');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Alícia Rodrigues', 'Vargas', '94442-885');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Pietro Araújo', 'Lima do Galho', '46147-915');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Alice Pereira', 'Pinto', '31997664');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Lucas Peixoto', 'Aragão', '39675-697');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sra. Maria Júlia Barros', 'Almeida', '45351052');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Marcelo Oliveira', 'da Conceição do Galho', '62845-805');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Guilherme Duarte', 'Guerra', '77465-362');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Caleb Gomes', 'Abreu', '61101853');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Otávio Pacheco', 'Ferreira', '91553-965');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Antonella Correia', 'Ribeiro de Porto', '47466584');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Marcos Vinicius Monteiro', 'Mendonça', '96790213');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Bianca Mendonça', 'Caldeira', '73778-582');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Larissa Farias', 'Machado da Mata', '54088-946');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Emanuel Barbosa', 'Guerra', '51437397');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Luiz Fernando Brito', 'Albuquerque', '28174500');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maitê Araújo', 'Rocha', '46334658');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Gael Araújo', 'Almeida', '88696-654');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Raquel Rezende', 'Andrade de Brito', '91772-699');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Antony Fonseca', 'Pastor', '78386-870');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Mariah Peixoto', 'Carvalho Alegre', '02251737');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Srta. Maria Cecília da Mota', 'Santos de Goiás', '54151-366');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Luísa da Cruz', 'Martins de Minas', '02781-339');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Eduarda Gonçalves', 'Teixeira de Goiás', '77989-473');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Calebe Caldeira', 'Gonçalves', '12062-960');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Otávio Brito', 'Fogaça Paulista', '31206858');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Luana da Cruz', 'Martins', '27109815');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Daniel Mendonça', 'Abreu', '11505497');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Lívia Pinto', 'da Rocha', '24807486');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Luiz Henrique Ramos', 'Duarte de Cunha', '54086-127');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Isis Sá', 'da Luz', '70641-223');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Srta. Bianca Gomes', 'Cavalcanti Verde', '61236599');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Leonardo Sales', 'Vargas de Lima', '18692823');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Jade Pinto', 'Almeida', '39592531');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Cecília da Cruz', 'Abreu', '76850-253');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Daniel Ramos', 'Moraes do Campo', '53592-628');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maria Siqueira', 'Costela de Vasconcelos', '83049663');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Eduardo Garcia', 'Pires Alegre', '15016319');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Nina Jesus', 'Leão', '01217864');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Rodrigo Melo', 'Câmara das Pedras', '88700052');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Gabriela Andrade', 'Borges da Mata', '11008653');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Ana Laura Araújo', 'Vargas', '62046-039');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Allana Nogueira', 'Rodrigues do Sul', '57879743');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Vitor Gabriel da Paz', 'Pinto da Mata', '80399167');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maya Monteiro', 'Farias de Sampaio', '42273-273');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Lunna da Rocha', 'Câmara do Oeste', '81950-254');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Maya Cavalcante', 'Fernandes das Flores', '44958-332');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Natália Pastor', 'Aparecida do Amparo', '31244-275');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Apollo Pires', 'Azevedo', '81693512');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Rael Cunha', 'Dias de Casa Grande', '51290-286');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Dr. Davi Silveira', 'Moura', '85635323');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Caroline Monteiro', 'da Costa da Praia', '61960-137');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Miguel Casa Grande', 'Novais de Goiás', '14615907');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Bruna Rezende', 'Castro', '15537-032');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Giovanna Cassiano', 'Oliveira', '29527610');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Sr. Yago Montenegro', 'da Costa Verde', '42893-949');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Henry Sá', 'Cavalcante do Sul', '81799-742');
INSERT INTO pessoa(nome, cidade, cep) VALUES('Bento Teixeira', 'Novais da Praia', '37230275');
